# Generated by Django 4.2.2 on 2024-03-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Id', models.IntegerField()),
                ('Sydney_Participant', models.IntegerField()),
                ('Syndey_Percentile', models.IntegerField()),
                ('Assesment_Area_Id', models.IntegerField()),
                ('Award_Id', models.IntegerField()),
                ('Class_ID', models.IntegerField()),
                ('Corret_anbswer_percentage_per_calss', models.IntegerField()),
                ('Correct_Answer', models.IntegerField()),
                ('Student_Id', models.IntegerField()),
                ('Particippant', models.IntegerField()),
                ('Student_score', models.IntegerField()),
                ('Subject_Id', models.IntegerField()),
                ('Category_Id', models.IntegerField()),
                ('Year_level_name', models.IntegerField()),
                ('Answer_Id', models.IntegerField()),
                ('Correct_answer_id', models.IntegerField()),
            ],
        ),
    ]
